# Generated by Django 4.1.5 on 2023-01-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False, verbose_name='активне')),
                ('location_city', models.CharField(max_length=50, verbose_name='місто')),
                ('location', models.CharField(max_length=250, verbose_name='адреса')),
                ('post_index', models.CharField(max_length=15, verbose_name='поштовий індекс')),
                ('open_days_start', models.CharField(max_length=15, verbose_name='перший робочий день')),
                ('open_days_end', models.CharField(max_length=15, verbose_name='останній робочий день')),
                ('open_hours_start', models.TimeField(verbose_name='початок робочого дня')),
                ('open_hours_end', models.TimeField(verbose_name='кінець робочого дня')),
                ('e_mail_1', models.EmailField(max_length=254, verbose_name='перший E_mail')),
                ('e_mail_2', models.EmailField(blank=True, default='', max_length=254, verbose_name='другий E_mail')),
                ('call_1', models.CharField(max_length=15, verbose_name='номер телефона')),
                ('call_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='номер телефона')),
                ('link_map', models.TextField(blank=True, max_length=500, null=True, verbose_name='посилання на мапу')),
                ('twitter', models.TextField(blank=True, max_length=50, null=True)),
                ('facebook', models.TextField(blank=True, max_length=50, null=True)),
                ('instagram', models.TextField(blank=True, max_length=50, null=True)),
                ('telegram', models.TextField(blank=True, max_length=50, null=True)),
                ('viber', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'загальна інформація',
                'verbose_name_plural': 'загальна інформація',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('message', models.TextField(max_length=500, verbose_name='Повідомлення')),
                ('archived', models.BooleanField(default=False, verbose_name='У архіві')),
                ('date_in', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('date_archiving', models.DateTimeField(auto_now=True, verbose_name='остання дія')),
            ],
            options={
                'verbose_name': 'Повідомлення від клієнта',
                'verbose_name_plural': 'Повідомлення від клієнта',
                'ordering': ('archived',),
            },
        ),
    ]
