# Generated by Django 4.1.5 on 2023-01-23 21:27

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Назва бренду')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Список брендів',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(verbose_name='Знижка')),
            ],
            options={
                'verbose_name_plural': 'Знижка товару',
                'ordering': ('percent',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Тип товару',
                'verbose_name_plural': 'Тип товару',
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=25, verbose_name='Назва товару')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True, max_length=2000, verbose_name='Опис товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вартість')),
                ('stock', models.PositiveIntegerField(verbose_name='Залишок на складі')),
                ('size_length', models.PositiveSmallIntegerField(verbose_name='Длина')),
                ('size_width', models.PositiveSmallIntegerField(verbose_name='Ширина')),
                ('size_height', models.PositiveSmallIntegerField(verbose_name='Висота')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
                ('material', models.CharField(max_length=25, verbose_name='Матеріал')),
                ('article', models.PositiveIntegerField(verbose_name='Артікул товару')),
                ('image1', models.ImageField(default='images/no_image.png', upload_to=product.models.Product.get_file_name, verbose_name='Зображення')),
                ('image2', models.ImageField(default='images/no_image.png', upload_to=product.models.Product.get_file_name, verbose_name='Зображення')),
                ('image3', models.ImageField(default='images/no_image.png', upload_to=product.models.Product.get_file_name, verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Наявність товару')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brands', verbose_name='Торгова марка')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.discount', verbose_name='Знижка "%"')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.subcategory', verbose_name='Тип товару')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ('brand', 'is_active'),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('parent', models.ManyToManyField(to='product.subcategory', verbose_name='Тип товару')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
