# Generated by Django 4.1.5 on 2023-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='со скидкой'),
        ),
    ]
