# Generated by Django 4.1.5 on 2023-02-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
