# Generated by Django 4.1.5 on 2023-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=11, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
