# Generated by Django 4.1.5 on 2023-01-23 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва тематики')),
            ],
            options={
                'verbose_name': 'Тематки купона',
                'verbose_name_plural': 'Тематики купонів',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='унікальний код')),
                ('valid_from', models.DateTimeField(verbose_name='дійсне від')),
                ('valid_to', models.DateTimeField(verbose_name='дійсне до')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка')),
                ('active', models.BooleanField(verbose_name='Дійсне')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.subjectcoupons', verbose_name='Тематика купону')),
            ],
            options={
                'verbose_name': 'Купон на знижку',
                'verbose_name_plural': 'Купони на знижку',
            },
        ),
    ]
