# Generated by Django 4.1.5 on 2023-01-23 21:27

from django.db import migrations, models
import django.db.models.deletion
import home_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=300, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to=home_page.models.HeroSection.get_file_name, verbose_name='Фото')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Відображення')),
            ],
            options={
                'verbose_name': 'слайди у шапці',
                'verbose_name_plural': 'слайди у шапці',
            },
        ),
        migrations.CreateModel(
            name='SeasonSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=50, verbose_name='Загальна інформація')),
                ('max_discount', models.PositiveSmallIntegerField(verbose_name='Максимальна знижка')),
                ('image', models.ImageField(upload_to=home_page.models.SeasonSale.get_file_name, verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Pозпродаж',
                'verbose_name_plural': 'Pозпродаж',
            },
        ),
        migrations.CreateModel(
            name='SeasonSaleVisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(unique=True, verbose_name='Відобразити')),
                ('left_block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_block', to='home_page.seasonsale', verbose_name='Лівий блок')),
                ('right_block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_block', to='home_page.seasonsale', verbose_name='Правий блок')),
            ],
            options={
                'verbose_name': 'Відображення розпродажу',
                'verbose_name_plural': 'Відображення розпродажу',
                'ordering': ('-is_visible',),
            },
        ),
    ]
