# Generated by Django 4.1.5 on 2023-01-23 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('department_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер відділення')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адреса')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Повідомлення')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='змінено')),
                ('processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='product.product')),
            ],
        ),
    ]
